spring.application.name=gateway
spring.config.import=optional:file:.env[.properties]
server.port=9999
server.servlet.session.timeout=30d

spring.security.oauth2.client.registration.keycloak.redirect-uri=${KEYCLOAK_OAUTH_CALLBACK}
spring.security.oauth2.client.registration.keycloak.client-id=${KEYCLOAK_CLIENT_ID}
spring.security.oauth2.client.registration.keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}
spring.security.oauth2.client.registration.keycloak.scope=openId,email
spring.security.oauth2.client.provider.keycloak.issuer-uri=${KEYCLOAK_ISSUER_URI}

gateway.services.urls.gateway=${GATEWAY_SERVICE_URL}
gateway.services.urls.users=${USER_SERVICE_URL}
gateway.services.urls.groups=${GROUP_SERVICE_URL}
gateway.services.urls.checkpoints=${CHECKPOINT_SERVICE_URL}
gateway.services.urls.invites=${INVITE_SERVICE_URL}
gateway.services.urls.trends=${TRENDS_SERVICE_URL}