spring.application.name=gateway
spring.config.import=optional:file:.env[.properties]
server.port=9999
server.servlet.session.timeout=30d

spring.security.oauth2.client.registration.keycloak.client-id=${KC_CLIENT_ID}
spring.security.oauth2.client.registration.keycloak.client-secret=${KC_CLIENT_SECRET}
spring.security.oauth2.client.registration.keycloak.scope=openid,email,usergroups
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri=${KC_REDIRECT_URI}

spring.security.oauth2.client.provider.keycloak.issuer-uri=${KC_ISSUER_URI}

gateway.services.urls.gateway=${GATEWAY_SERVICE_URL}
gateway.services.urls.users=${USER_SERVICE_URL}
gateway.services.urls.groups=${GROUP_SERVICE_URL}
gateway.services.urls.checkpoints=${CHECKPOINT_SERVICE_URL}
gateway.services.urls.invites=${INVITE_SERVICE_URL}
gateway.services.urls.trends=${TRENDS_SERVICE_URL}